In [ ]:
# import necessary libraries
import numpy as np
import tensorflow as tf

In [2]:
##Training Phase

In [3]:
# load dataset
with open("/content/sriLanka.txt", 'r', encoding='utf-8') as file:
    sriLanka = file.read()

In [4]:
sriLanka


'Sri Lanka, often referred to as the "Pearl of the Indian Ocean," is a captivating island nation with a rich tapestry of history, culture, and natural beauty. Situated off the southeastern coast of India, this island boasts diverse landscapes that range from pristine beaches and lush rainforests to rolling tea plantations and rugged mountain ranges. The island’s natural beauty and strategic location have made it a significant player in the region for centuries.\n\nThe geography of Sri Lanka is marked by its impressive variety. The central highlands, home to the country\'s highest peak, Pidurutalagala, offer a cool climate and picturesque views. These highlands are also the heart of Sri Lanka\'s tea industry, with expansive plantations producing some of the world’s finest tea. In contrast, the coastal areas are renowned for their stunning beaches and vibrant marine life, making them popular destinations for tourists and locals alike.\n\nThe climate in Sri Lanka is tropical and maritime,

In [5]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts([sriLanka])

In [8]:
tokenizer.get_config()


{'num_words': None,
 'filters': '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
 'lower': True,
 'split': ' ',
 'char_level': False,
 'oov_token': None,
 'document_count': 1,
 'word_counts': '{"sri": 22, "lanka": 12, "often": 3, "referred": 2, "to": 22, "as": 6, "the": 78, "pearl": 1, "of": 42, "indian": 3, "ocean": 2, "is": 25, "a": 26, "captivating": 1, "island": 2, "nation": 1, "with": 15, "rich": 4, "tapestry": 1, "history": 4, "culture": 2, "and": 73, "natural": 7, "beauty": 5, "situated": 1, "off": 1, "southeastern": 1, "coast": 1, "india": 1, "this": 5, "boasts": 1, "diverse": 5, "landscapes": 2, "that": 2, "range": 3, "from": 5, "pristine": 2, "beaches": 3, "lush": 1, "rainforests": 1, "rolling": 1, "tea": 5, "plantations": 2, "rugged": 1, "mountain": 1, "ranges": 1, "island\\u2019s": 4, "strategic": 2, "location": 2, "have": 1, "made": 3, "it": 4, "significant": 6, "player": 1, "in": 17, "region": 1, "for": 18, "centuries": 2, "geography": 1, "marked": 2, "by": 6, "its": 17, "impressi

In [7]:
tokenizer.get_config()['filters']

'!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'

In [9]:
tokenizer.word_index


{'the': 1,
 'and': 2,
 'of': 3,
 'a': 4,
 'is': 5,
 'sri': 6,
 'to': 7,
 'for': 8,
 'in': 9,
 'its': 10,
 'with': 11,
 'lanka': 12,
 'are': 13,
 'natural': 14,
 'cultural': 15,
 'as': 16,
 'significant': 17,
 'by': 18,
 'also': 19,
 'country’s': 20,
 'world': 21,
 'beauty': 22,
 'this': 23,
 'diverse': 24,
 'from': 25,
 'tea': 26,
 'ancient': 27,
 'one': 28,
 'on': 29,
 'tourism': 30,
 'efforts': 31,
 'rich': 32,
 'history': 33,
 'island’s': 34,
 'it': 35,
 "lanka's": 36,
 'marine': 37,
 'lankan': 38,
 'being': 39,
 'country': 40,
 'has': 41,
 'economic': 42,
 'often': 43,
 'indian': 44,
 'range': 45,
 'beaches': 46,
 'made': 47,
 'variety': 48,
 'highlands': 49,
 'home': 50,
 'areas': 51,
 'renowned': 52,
 'vibrant': 53,
 'making': 54,
 'popular': 55,
 'monsoon': 56,
 'while': 57,
 'biodiversity': 58,
 'many': 59,
 'species': 60,
 'heritage': 61,
 'temples': 62,
 'city': 63,
 'around': 64,
 'famous': 65,
 'diversity': 66,
 'most': 67,
 'which': 68,
 'known': 69,
 'curry': 70,
 'includ

In [10]:
input_sequences = []
for sentence in sriLanka.split('\n'):
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequences.append(sequence)

In [11]:
input_sequences[:5]

[[6, 12],
 [6, 12, 43],
 [6, 12, 43, 79],
 [6, 12, 43, 79, 7],
 [6, 12, 43, 79, 7, 16]]

In [12]:
max_length = max([len(input_sequence) for input_sequence in input_sequences])
max_length

145

In [13]:
# add padding
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))

In [14]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  6, 12, 43], dtype=int32)

In [15]:
# divide dataset into feature set (X) and labels (y)
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [16]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6], dtype=int32)

In [17]:
y

array([ 12,  43,  79, ...,   4, 520, 521], dtype=int32)

In [18]:
# number of words
num_classes = len(tokenizer.word_index)+1

In [19]:
# one-hot encoding labels
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))

In [20]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [21]:
# model building
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 144, 80)           41760     
                                                                 
 lstm (LSTM)                 (None, 100)               72400     
                                                                 
 dense (Dense)               (None, 522)               52722     
                                                                 
Total params: 166882 (651.88 KB)
Trainable params: 166882 (651.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
# compile the model
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [24]:
# model training
history = model.fit(X, y, epochs=100)

Epoch 1/100
36/36 [==============================] - 7s 135ms/step - loss: 6.0578 - accuracy: 0.0533
Epoch 2/100
36/36 [==============================] - 4s 105ms/step - loss: 5.6522 - accuracy: 0.0655
Epoch 3/100
36/36 [==============================] - 4s 107ms/step - loss: 5.5586 - accuracy: 0.0690
Epoch 4/100
36/36 [==============================] - 5s 139ms/step - loss: 5.5179 - accuracy: 0.0699
Epoch 5/100
36/36 [==============================] - 4s 105ms/step - loss: 5.4539 - accuracy: 0.0917
Epoch 6/100
36/36 [==============================] - 4s 104ms/step - loss: 5.3671 - accuracy: 0.0969
Epoch 7/100
36/36 [==============================] - 5s 133ms/step - loss: 5.2649 - accuracy: 0.0847
Epoch 8/100
36/36 [==============================] - 4s 109ms/step - loss: 5.1652 - accuracy: 0.1039
Epoch 9/100
36/36 [==============================] - 4s 105ms/step - loss: 5.0536 - accuracy: 0.1109
Epoch 10/100
36/36 [==============================] - 4s 123ms/step - loss: 4.9432 - accura

In [27]:
input_text = "Sri Lanka is a"
for i in range(10):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 [==============================] - 0s 54ms/step
Sri Lanka is a country of immense beauty rich history and cultural diversity its
